// <auto-generated />
using System;
using API.DbConects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250510150847_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("id_gio_hang_chi_tiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_khach_hang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("bit");

                    b.HasKey("id_gio_hang_chi_tiet");

                    b.HasIndex("id_khach_hang");

                    b.HasIndex("id_san_pham_chi_tiet");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.HoaDon", b =>
                {
                    b.Property<Guid>("id_hoa_don")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dia_chi_nhan_hang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghi_chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("id_khach_hang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_khuyen_mai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_phuong_thuc_thanh_toan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("loai_hoa_don")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma_hoa_don")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("sdt_khach_hang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("so_tien_khuyen_mai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ten_khach_hang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_nhan_vien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("tong_tien_don_hang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("tong_tien_phai_thanh_toan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("trang_thai_hoa_don")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_hoa_don");

                    b.HasIndex("id_khach_hang");

                    b.HasIndex("id_khuyen_mai");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_phuong_thuc_thanh_toan");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("id_hoa_don_chi_tiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("don_gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ghi_chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("gia_sau_giam_gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("gia_tri_khuyen_mai_cua_hoa_don_cho_hdct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("id_hoa_don")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_hoa_don_chi_tiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaySua")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("nguoiSuaid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<string>("ten_kich_co")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_mau_sac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("thanh_tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_hoa_don_chi_tiet");

                    b.HasIndex("id_hoa_don");

                    b.HasIndex("id_san_pham_chi_tiet");

                    b.HasIndex("nguoiSuaid_nhan_vien");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("id_phuong_thuc_thanh_toan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_phuong_thuc_thanh_toan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_phuong_thuc_thanh_toan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("bit");

                    b.HasKey("id_phuong_thuc_thanh_toan");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Khuyen_Mai.GiamGia", b =>
                {
                    b.Property<Guid>("id_giam_gia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("gia_tri_giam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("id_nguoi_cap_nhat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("kieu_giam_gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma_giam_gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_cap_nhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("so_luong_da_su_dung")
                        .HasColumnType("int");

                    b.Property<int>("so_luong_toi_da")
                        .HasColumnType("int");

                    b.Property<string>("ten_giam_gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoi_gian_bat_dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoi_gian_ket_thuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_giam_gia");

                    b.HasIndex("id_nguoi_cap_nhat");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Khuyen_Mai.KhuyenMai", b =>
                {
                    b.Property<Guid>("id_khuyen_mai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("gia_tri_don_hang_toi_thieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("gia_tri_giam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("gia_tri_giam_toi_da")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("kieu_khuyen_mai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma_khuyen_mai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("so_luong_da_su_dung")
                        .HasColumnType("int");

                    b.Property<int>("so_luong_toi_da")
                        .HasColumnType("int");

                    b.Property<string>("ten_khuyen_mai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoi_gian_bat_dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoi_gian_ket_thuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_khuyen_mai");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.ChatLieu", b =>
                {
                    b.Property<Guid>("id_chat_lieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_chat_lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_chat_lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_chat_lieu");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("ChatLieus");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.DanhMuc", b =>
                {
                    b.Property<Guid>("id_danh_muc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_danh_muc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_danh_muc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_danh_muc");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.HinhAnh", b =>
                {
                    b.Property<Guid>("id_hinh_anh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_hinh_anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_hinh_anh");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("HinhAnhs");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.HinhAnhSanPhamChiTiet", b =>
                {
                    b.Property<Guid>("id_hinh_anh_san_pham_chi_tiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_hinh_anh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id_hinh_anh_san_pham_chi_tiet");

                    b.HasIndex("id_hinh_anh");

                    b.HasIndex("id_san_pham_chi_tiet");

                    b.ToTable("HinhAnhSanPhamChiTiet");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.KichCo", b =>
                {
                    b.Property<Guid>("id_kich_co")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_kich_co")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_kich_co")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_kich_co");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("KichCos");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.KieuDang", b =>
                {
                    b.Property<Guid>("id_kieu_dang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_kieu_dang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_kieu_dang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_kieu_dang");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("KieuDangs");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.MauSac", b =>
                {
                    b.Property<Guid>("id_mau_sac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_mau_sac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_mau_sac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_mau_sac");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.SanPham", b =>
                {
                    b.Property<Guid>("id_san_pham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_anh_mac_dinh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_chat_lieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_danh_muc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_kieu_dang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_thuong_hieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_xuat_xu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_san_pham");

                    b.HasIndex("id_anh_mac_dinh")
                        .IsUnique()
                        .HasFilter("[id_anh_mac_dinh] IS NOT NULL");

                    b.HasIndex("id_chat_lieu");

                    b.HasIndex("id_danh_muc");

                    b.HasIndex("id_kieu_dang");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_thuong_hieu");

                    b.HasIndex("id_xuat_xu");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("gia_ban")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("gia_nhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("id_giam_gia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_kich_co")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_mau_sac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_san_pham_chi_tiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_san_pham_chi_tiet");

                    b.HasIndex("id_giam_gia");

                    b.HasIndex("id_kich_co");

                    b.HasIndex("id_mau_sac");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_san_pham");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.ThuongHieu", b =>
                {
                    b.Property<Guid>("id_thuong_hieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_thuong_hieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_thuong_hieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_thuong_hieu");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.XuatXu", b =>
                {
                    b.Property<Guid>("id_xuat_xu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_xuat_xu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_xuat_xu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_xuat_xu");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("XuatXus");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.DiaChi", b =>
                {
                    b.Property<Guid>("id_dia_chi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("dia_chi_mac_dinh")
                        .HasColumnType("bit");

                    b.Property<string>("huyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_khach_hang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ngay_sua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngay_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_dia_chi");

                    b.HasIndex("id_khach_hang");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.KhachHang", b =>
                {
                    b.Property<Guid>("id_khach_hang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioi_tinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("id_tai_khoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_khach_hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("so_dien_thoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_khach_hang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_khach_hang");

                    b.HasIndex("id_tai_khoan")
                        .IsUnique()
                        .HasFilter("[id_tai_khoan] IS NOT NULL");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", b =>
                {
                    b.Property<Guid>("id_nhan_vien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dia_chi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioi_tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_tai_khoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_nhan_vien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_sinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("so_dien_thoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_nhan_vien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_nhan_vien");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_tai_khoan")
                        .IsUnique();

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            id_nhan_vien = new Guid("00000000-0000-0000-0000-000000000001"),
                            cccd = "000000000001",
                            dia_chi = "Hà Nội",
                            email = "datntph32970@gmail.com",
                            gioi_tinh = "Nam",
                            id_nguoi_tao = new Guid("11111111-1111-1111-1111-111111111111"),
                            id_tai_khoan = new Guid("11111111-1111-1111-1111-111111111111"),
                            ma_nhan_vien = "TK00000001",
                            ngay_sinh = new DateTime(2004, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngay_tao = new DateTime(2025, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            so_dien_thoai = "0369104997",
                            ten_nhan_vien = "họ và tên admin 1",
                            trang_thai = "HoatDong"
                        },
                        new
                        {
                            id_nhan_vien = new Guid("33333333-3333-3333-3333-333333333333"),
                            cccd = "000000000000",
                            dia_chi = "Hà Nội",
                            email = "nthanhdat7112004@gmail.com",
                            gioi_tinh = "Nam",
                            id_nguoi_tao = new Guid("11111111-1111-1111-1111-111111111111"),
                            id_tai_khoan = new Guid("22222222-2222-2222-2222-222222222222"),
                            ma_nhan_vien = "TK00000002",
                            ngay_sinh = new DateTime(2004, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngay_tao = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            so_dien_thoai = "0111111111",
                            ten_nhan_vien = "họ và tên nhân viên 1",
                            trang_thai = "HoatDong"
                        });
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.TaiKhoan", b =>
                {
                    b.Property<Guid>("id_tai_khoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("chuc_vu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("da_doi_mat_khau")
                        .HasColumnType("bit");

                    b.Property<string>("ma_tai_khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mat_khau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_dang_nhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tai_khoan");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            id_tai_khoan = new Guid("11111111-1111-1111-1111-111111111111"),
                            chuc_vu = "Admin",
                            da_doi_mat_khau = false,
                            ma_tai_khoan = "TK00000001",
                            mat_khau = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            ten_dang_nhap = "admin",
                            trang_thai = "HoatDong"
                        },
                        new
                        {
                            id_tai_khoan = new Guid("22222222-2222-2222-2222-222222222222"),
                            chuc_vu = "NhanVien",
                            da_doi_mat_khau = false,
                            ma_tai_khoan = "TK00000002",
                            mat_khau = "fa5a1d3e67d2193b86bc68c7db41bd84f242fe4e41146ef4a4a5441254d2a3f7",
                            ten_dang_nhap = "nhanvien",
                            trang_thai = "HoatDong"
                        });
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.GioHangChiTiet", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.KhachHang", "KhachHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("id_khach_hang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("id_san_pham_chi_tiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.HoaDon", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("id_khach_hang");

                    b.HasOne("API.DbConects.Entities.Entities_Khuyen_Mai.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("id_khuyen_mai");

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaHoaDons")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoHoaDons")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_Hoa_Don.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDons")
                        .HasForeignKey("id_phuong_thuc_thanh_toan");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.HoaDonChiTiet", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Hoa_Don.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("id_hoa_don")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("id_san_pham_chi_tiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "nguoiSua")
                        .WithMany("SuaHoaDonChiTiets")
                        .HasForeignKey("nguoiSuaid_nhan_vien");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");

                    b.Navigation("nguoiSua");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Khuyen_Mai.GiamGia", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaGiamGias")
                        .HasForeignKey("id_nguoi_cap_nhat")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoGiamGias")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Khuyen_Mai.KhuyenMai", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaKhuyenMais")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoKhuyenMais")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.ChatLieu", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaChatLieus")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoChatLieus")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.DanhMuc", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaDanhMucs")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoDanhMucs")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.HinhAnh", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaHinhAnhs")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoHinhAnhs")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.HinhAnhSanPhamChiTiet", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.HinhAnh", "HinhAnhs")
                        .WithMany("HinhAnhSanPhamChiTiets")
                        .HasForeignKey("id_hinh_anh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.SanPhamChiTiet", "SanPhamChiTiets")
                        .WithMany("HinhAnhSanPhamChiTiets")
                        .HasForeignKey("id_san_pham_chi_tiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HinhAnhs");

                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.KichCo", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaKichCos")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoKichCos")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.KieuDang", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaKieuDangs")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoKieuDangs")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.MauSac", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaMauSacs")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoMauSacs")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.SanPham", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.HinhAnh", "anhMacDinh")
                        .WithOne("SanPham")
                        .HasForeignKey("API.DbConects.Entities.Entities_San_Pham.SanPham", "id_anh_mac_dinh");

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_chat_lieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_danh_muc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.KieuDang", "KieuDang")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_kieu_dang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaSanPhams")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoSanPhams")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_thuong_hieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.XuatXu", "XuatXu")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_xuat_xu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("KieuDang");

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");

                    b.Navigation("ThuongHieu");

                    b.Navigation("XuatXu");

                    b.Navigation("anhMacDinh");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.SanPhamChiTiet", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Khuyen_Mai.GiamGia", "GiamGia")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("id_giam_gia");

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.KichCo", "KichCo")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("id_kich_co")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.MauSac", "MauSac")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("id_mau_sac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaSanPhamChiTiets")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoSanPhamChiTiets")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_San_Pham.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("id_san_pham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiamGia");

                    b.Navigation("KichCo");

                    b.Navigation("MauSac");

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.ThuongHieu", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaThuongHieus")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoThuongHieus")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.XuatXu", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany("SuaXuatXus")
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany("TaoXuatXus")
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.DiaChi", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.KhachHang", "KhachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("id_khach_hang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.KhachHang", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("API.DbConects.Entities.Entities_Tai_Khoan.KhachHang", "id_tai_khoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", b =>
                {
                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.TaiKhoan", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Entities_Tai_Khoan.TaiKhoan", "TaiKhoanNhanVien")
                        .WithOne("NhanVien")
                        .HasForeignKey("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", "id_tai_khoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiTao");

                    b.Navigation("TaiKhoanNhanVien");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Hoa_Don.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Khuyen_Mai.GiamGia", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Khuyen_Mai.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.HinhAnh", b =>
                {
                    b.Navigation("HinhAnhSanPhamChiTiets");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.KieuDang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.SanPhamChiTiet", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HinhAnhSanPhamChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_San_Pham.XuatXu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.NhanVien", b =>
                {
                    b.Navigation("SuaChatLieus");

                    b.Navigation("SuaDanhMucs");

                    b.Navigation("SuaGiamGias");

                    b.Navigation("SuaHinhAnhs");

                    b.Navigation("SuaHoaDonChiTiets");

                    b.Navigation("SuaHoaDons");

                    b.Navigation("SuaKhuyenMais");

                    b.Navigation("SuaKichCos");

                    b.Navigation("SuaKieuDangs");

                    b.Navigation("SuaMauSacs");

                    b.Navigation("SuaSanPhamChiTiets");

                    b.Navigation("SuaSanPhams");

                    b.Navigation("SuaThuongHieus");

                    b.Navigation("SuaXuatXus");

                    b.Navigation("TaoChatLieus");

                    b.Navigation("TaoDanhMucs");

                    b.Navigation("TaoGiamGias");

                    b.Navigation("TaoHinhAnhs");

                    b.Navigation("TaoHoaDons");

                    b.Navigation("TaoKhuyenMais");

                    b.Navigation("TaoKichCos");

                    b.Navigation("TaoKieuDangs");

                    b.Navigation("TaoMauSacs");

                    b.Navigation("TaoSanPhamChiTiets");

                    b.Navigation("TaoSanPhams");

                    b.Navigation("TaoThuongHieus");

                    b.Navigation("TaoXuatXus");
                });

            modelBuilder.Entity("API.DbConects.Entities.Entities_Tai_Khoan.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
