// <auto-generated />
using System;
using API.DbConects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250215071018_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("id_gio_hang_chi_tiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_khach_hang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("bit");

                    b.HasKey("id_gio_hang_chi_tiet");

                    b.HasIndex("id_khach_hang");

                    b.HasIndex("id_san_pham_chi_tiet");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.HoaDon", b =>
                {
                    b.Property<Guid>("id_hoa_don")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dia_chi_nhan_hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_khach_hang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_khuyen_mai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_phuong_thuc_thanh_toan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_trang_thai_hoa_don")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_hoa_don")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("sdt_khach_hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("so_tien_khuyen_mai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ten_khach_hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_nhan_vien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tong_tien_don_hang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tong_tien_phai_thanh_toan")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_hoa_don");

                    b.HasIndex("id_khach_hang");

                    b.HasIndex("id_khuyen_mai");

                    b.HasIndex("id_nhan_vien");

                    b.HasIndex("id_phuong_thuc_thanh_toan");

                    b.HasIndex("id_trang_thai_hoa_don");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("id_hoa_don_chi_tiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("don_gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_hoa_don")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_hoa_don_chi_tiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<decimal>("thanh_tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("bit");

                    b.HasKey("id_hoa_don_chi_tiet");

                    b.HasIndex("id_hoa_don");

                    b.HasIndex("id_san_pham_chi_tiet");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("id_phuong_thuc_thanh_toan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_phuong_thuc_thanh_toan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_phuong_thuc_thanh_toan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("bit");

                    b.HasKey("id_phuong_thuc_thanh_toan");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.TrangThaiHoaDon", b =>
                {
                    b.Property<Guid>("id_trang_thai_hoa_don")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_trang_thai_hoa_don")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_trang_thai_hoa_don")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trang_thai")
                        .HasColumnType("bit");

                    b.HasKey("id_trang_thai_hoa_don");

                    b.ToTable("TrangThaiHoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Khuyen_Mai.GiamGia", b =>
                {
                    b.Property<Guid>("id_giam_gia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_cap_nhat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("loai_giam_gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_cap_nhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_giam_gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoi_gian_bat_dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoi_gian_ket_thuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_giam_gia");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_cap_nhat");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("API.DbConects.Entities.Khuyen_Mai.GiamGiaSanPhamChiTiet", b =>
                {
                    b.Property<Guid>("id_giam_gia_san_pham_chi_tiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_giam_gia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_cap_nhat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ngay_cap_nhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.HasKey("id_giam_gia_san_pham_chi_tiet");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_giam_gia");

                    b.HasIndex("id_nguoi_cap_nhat");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_san_pham_chi_tiet")
                        .IsUnique();

                    b.ToTable("GiamGiaSanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Khuyen_Mai.KhuyenMai", b =>
                {
                    b.Property<Guid>("id_khuyen_mai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("gia_tri_giam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("gia_tri_giam_toi_da")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("gia_tri_giam_toi_thieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("kieu_giam_gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma_khuyen_mai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("so_luong_da_su_dung")
                        .HasColumnType("int");

                    b.Property<int>("so_luong_toi_da")
                        .HasColumnType("int");

                    b.Property<string>("ten_khuyen_mai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoi_gian_bat_dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoi_gian_ket_thuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_khuyen_mai");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.ChatLieu", b =>
                {
                    b.Property<Guid>("id_chat_lieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_chat_lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_chat_lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_chat_lieu");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("ChatLieus");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.HinhAnh", b =>
                {
                    b.Property<Guid>("id_hinh_anh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_hinh_anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_hinh_anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_hinh_anh");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_san_pham_chi_tiet");

                    b.ToTable("HinhAnhs");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.KichCo", b =>
                {
                    b.Property<Guid>("id_kich_co")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_kich_co")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_kich_co")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_kich_co");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("KichCos");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.KieuDang", b =>
                {
                    b.Property<Guid>("id_kieu_dang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_kieu_dang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_kieu_dang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_kieu_dang");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("KieuDangs");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.MauSac", b =>
                {
                    b.Property<Guid>("id_mau_sac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_mau_sac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_mau_sac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_mau_sac");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.SanPham", b =>
                {
                    b.Property<Guid>("id_san_pham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_chat_lieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_kieu_dang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_thuong_hieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_xuat_xu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_san_pham");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_chat_lieu");

                    b.HasIndex("id_kieu_dang");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_thuong_hieu");

                    b.HasIndex("id_xuat_xu");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("id_san_pham_chi_tiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("gia_ban")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("gia_nhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("id_kich_co")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_mau_sac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_san_pham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_san_pham_chi_tiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<decimal>("so_tien_giam_gia_theo_chuong_trinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_san_pham_chi_tiet");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_kich_co");

                    b.HasIndex("id_mau_sac");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_san_pham");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.ThuongHieu", b =>
                {
                    b.Property<Guid>("id_thuong_hieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_thuong_hieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_thuong_hieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_thuong_hieu");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.XuatXu", b =>
                {
                    b.Property<Guid>("id_xuat_xu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhanVienid_nhan_vien1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("id_nguoi_sua")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_xuat_xu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_xuat_xu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_xuat_xu");

                    b.HasIndex("NhanVienid_nhan_vien");

                    b.HasIndex("NhanVienid_nhan_vien1");

                    b.HasIndex("id_nguoi_sua");

                    b.HasIndex("id_nguoi_tao");

                    b.ToTable("XuatXus");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.DiaChi", b =>
                {
                    b.Property<Guid>("id_dia_chi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dia_chi_mac_dinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("huyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_khach_hang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ngay_sua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngay_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_dia_chi");

                    b.HasIndex("id_khach_hang");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.KhachHang", b =>
                {
                    b.Property<Guid>("id_khach_hang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioi_tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_tai_khoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_khach_hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_sinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("so_dien_thoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_khach_hang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_khach_hang");

                    b.HasIndex("id_tai_khoan")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.NhanVien", b =>
                {
                    b.Property<Guid>("id_nhan_vien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioi_tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_nguoi_tao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_tai_khoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_nhan_vien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_sinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("so_dien_thoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_nhan_vien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_nhan_vien");

                    b.HasIndex("id_nguoi_tao");

                    b.HasIndex("id_tai_khoan")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.TaiKhoan", b =>
                {
                    b.Property<Guid>("id_tai_khoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("chuc_vu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma_tai_khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mat_khau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_dang_nhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_tai_khoan");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.GioHangChiTiet", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.KhachHang", "KhachHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("id_khach_hang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("id_san_pham_chi_tiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.HoaDon", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("id_khach_hang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Khuyen_Mai.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("id_khuyen_mai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NhanVien")
                        .WithMany("TaoHoaDons")
                        .HasForeignKey("id_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Hoa_Don.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDons")
                        .HasForeignKey("id_phuong_thuc_thanh_toan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Hoa_Don.TrangThaiHoaDon", "TrangThaiHoaDon")
                        .WithMany("HoaDons")
                        .HasForeignKey("id_trang_thai_hoa_don")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");

                    b.Navigation("PhuongThucThanhToan");

                    b.Navigation("TrangThaiHoaDon");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.HoaDonChiTiet", b =>
                {
                    b.HasOne("API.DbConects.Entities.Hoa_Don.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("id_hoa_don")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.SanPhamChiTiet", "SanPhamChiTiets")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("id_san_pham_chi_tiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Khuyen_Mai.GiamGia", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaGiamGias")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoGiamGias")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_cap_nhat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Khuyen_Mai.GiamGiaSanPhamChiTiet", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaGiamGiaSanPhamChiTiets")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoGiamGiaSanPhamChiTiets")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Khuyen_Mai.GiamGia", "GiamGia")
                        .WithMany("GiamGiaSanPhamChiTiets")
                        .HasForeignKey("id_giam_gia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_cap_nhat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithOne("GiamGiaSanPhamChiTiets")
                        .HasForeignKey("API.DbConects.Entities.Khuyen_Mai.GiamGiaSanPhamChiTiet", "id_san_pham_chi_tiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiamGia");

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("API.DbConects.Entities.Khuyen_Mai.KhuyenMai", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaKhuyenMais")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoKhuyenMais")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.ChatLieu", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaChatLieus")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoChatLieus")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.HinhAnh", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaHinhAnhs")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoHinhAnhs")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.SanPhamChiTiet", "SanPhamChiTiets")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("id_san_pham_chi_tiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");

                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.KichCo", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaKichCos")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoKichCos")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.KieuDang", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaKieuDangs")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoKieuDangs")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.MauSac", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaMauSacs")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoMauSacs")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.SanPham", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaSanPhams")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoSanPhams")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.San_Pham.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_chat_lieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.KieuDang", "KieuDang")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_kieu_dang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_thuong_hieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.XuatXu", "XuatXu")
                        .WithMany("SanPhams")
                        .HasForeignKey("id_xuat_xu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("KieuDang");

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");

                    b.Navigation("ThuongHieu");

                    b.Navigation("XuatXu");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.SanPhamChiTiet", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaSanPhamChiTiets")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoSanPhamChiTiets")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.San_Pham.KichCo", "KichCo")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("id_kich_co")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.MauSac", "MauSac")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("id_mau_sac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.San_Pham.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("id_san_pham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KichCo");

                    b.Navigation("MauSac");

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.ThuongHieu", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaThuongHieus")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoThuongHieus")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.XuatXu", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("SuaXuatXus")
                        .HasForeignKey("NhanVienid_nhan_vien");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", null)
                        .WithMany("TaoXuatXus")
                        .HasForeignKey("NhanVienid_nhan_vien1");

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiSua")
                        .WithMany()
                        .HasForeignKey("id_nguoi_sua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiSua");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.DiaChi", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.KhachHang", "KhachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("id_khach_hang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.KhachHang", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("API.DbConects.Entities.Tai_Khoan.KhachHang", "id_tai_khoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.NhanVien", b =>
                {
                    b.HasOne("API.DbConects.Entities.Tai_Khoan.TaiKhoan", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("id_nguoi_tao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DbConects.Entities.Tai_Khoan.TaiKhoan", "TaiKhoanNhanVien")
                        .WithOne("NhanVien")
                        .HasForeignKey("API.DbConects.Entities.Tai_Khoan.NhanVien", "id_tai_khoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiTao");

                    b.Navigation("TaiKhoanNhanVien");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Hoa_Don.TrangThaiHoaDon", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Khuyen_Mai.GiamGia", b =>
                {
                    b.Navigation("GiamGiaSanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.Khuyen_Mai.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.KieuDang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.SanPhamChiTiet", b =>
                {
                    b.Navigation("GiamGiaSanPhamChiTiets");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HinhAnhs");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.San_Pham.XuatXu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.NhanVien", b =>
                {
                    b.Navigation("SuaChatLieus");

                    b.Navigation("SuaGiamGiaSanPhamChiTiets");

                    b.Navigation("SuaGiamGias");

                    b.Navigation("SuaHinhAnhs");

                    b.Navigation("SuaKhuyenMais");

                    b.Navigation("SuaKichCos");

                    b.Navigation("SuaKieuDangs");

                    b.Navigation("SuaMauSacs");

                    b.Navigation("SuaSanPhamChiTiets");

                    b.Navigation("SuaSanPhams");

                    b.Navigation("SuaThuongHieus");

                    b.Navigation("SuaXuatXus");

                    b.Navigation("TaoChatLieus");

                    b.Navigation("TaoGiamGiaSanPhamChiTiets");

                    b.Navigation("TaoGiamGias");

                    b.Navigation("TaoHinhAnhs");

                    b.Navigation("TaoHoaDons");

                    b.Navigation("TaoKhuyenMais");

                    b.Navigation("TaoKichCos");

                    b.Navigation("TaoKieuDangs");

                    b.Navigation("TaoMauSacs");

                    b.Navigation("TaoSanPhamChiTiets");

                    b.Navigation("TaoSanPhams");

                    b.Navigation("TaoThuongHieus");

                    b.Navigation("TaoXuatXus");
                });

            modelBuilder.Entity("API.DbConects.Entities.Tai_Khoan.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
